version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --user postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s
  backend:
    # change kniffel-server to match your directory name of the spring REST api
    build: ./kniffel-server
    ports:
      - 8080:8080
    environment:
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8080/actuator/health"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s
  frontend:
    # change kniffel-client to match your directory name of the vue client
    build: ./kniffel-client
    ports:
      - 80:80
    depends_on:
      backend:
        condition: service_healthy